name: dispatcher

description: Dispatcher generator

files: [lib],
version: 0.1.9

bin:
    dispatcher: cli.php

author:
    name: César Rodas
    email: crodas@php.net

dependencies:
    - github:crodas/Notoj
    - github:crodas/Artifex
    - github:symfony/Console
