<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */


spl_autoload_register(function ($class) {
    /*
        This array has a map of (class => file)
    */

    // classes {{{
    static $classes = array (
  'dispatcher\\compiler\\component' => '/Compiler/Component.php',
  'dispatcher\\compiler\\url' => '/Compiler/Url.php',
  'dispatcher\\compiler\\urlgroup' => '/UrlGroup.php',
  'dispatcher\\compiler' => '/Compiler.php',
  'dispatcher\\generator' => '/Generator.php',
);
    // }}}


    $class = strtolower($class);
    if (isset($classes[$class])) {

        if (!class_exists($class, false)) {

            require __DIR__  . $classes[$class];

        }
        return true;
    }

    return false;
});


